package provider

import (
	"context"
	"time"

	"github.com/ya222/defib-my-agent/internal/detect"
)

// Provider drives one external agent CLI. Adapters implement this and register themselves.
// Adapters are kept free of scheduling/state-machine logic — they only build commands, parse
// sessions, and provide detection rules.
type Provider interface {
	// Name is the stable identifier used in config and the CLI (e.g. "claude").
	Name() string

	// Capabilities describes what this provider supports.
	Capabilities() Capabilities

	// BuildStart returns the argv (argv[0] is the executable) to begin a NEW session for the
	// task, plus any environment additions. If the provider supports client-supplied session
	// ids, the returned command MUST embed task.SessionRef (pre-generated by defib).
	BuildStart(task TaskSpec) (Command, error)

	// BuildResume returns the argv to CONTINUE an existing session identified by sessionRef.
	// Only called when Capabilities.Resume is true and a sessionRef is known.
	BuildResume(task TaskSpec, sessionRef string) (Command, error)

	// ExtractSessionRef inspects a finished attempt's output and returns the provider's
	// session id if it can be discovered from output. Returns ("", false) if unknown or if
	// the ref was pre-generated (defib already knows it).
	ExtractSessionRef(out AttemptOutput) (string, bool)

	// DetectionRules returns the provider's built-in rules (see docs/detection.md). The
	// engine merges these with user-configured rules.
	DetectionRules() []detect.Rule

	// CheckAvailability optionally reports whether the provider is usable again after a
	// QUOTA_EXHAUSTED outcome. Returns Unsupported if the provider offers no cheap check.
	CheckAvailability(ctx context.Context, task TaskSpec) (Availability, error)
}

// Capabilities describes what a Provider supports.
type Capabilities struct {
	Resume           bool // supports native session resume
	ClientSuppliedID bool // caller may choose the session id up front
	Headless         bool // supports non-interactive run with capturable output
	Interactive      bool // supports PTY-attached interactive run
	StructuredOutput bool // can emit machine-readable (e.g. JSON) output
}

// Command is the argv and environment additions needed to start or resume a provider process.
type Command struct {
	Argv []string          // argv[0] is the executable (resolved via config binary path or PATH)
	Env  map[string]string // additional env vars merged over the daemon environment
}

// TaskSpec describes the task an Attempt is driving, as passed to BuildStart/BuildResume.
type TaskSpec struct {
	Prompt         string   // initial instruction (may be empty if PassthroughArgs carries it)
	Passthrough    []string // extra argv appended after adapter-controlled flags (after `--`)
	Cwd            string
	Mode           string         // "headless" | "interactive"
	SessionRef     string         // pre-generated id if Capabilities.ClientSuppliedID, else ""
	Model          string         // optional provider model override from config
	ProviderConfig map[string]any // provider-scoped config block (see docs/configuration.md)
}

// Availability is the result of a CheckAvailability probe.
type Availability struct {
	State  AvailabilityState // Available | Unavailable | Unsupported
	NextAt *time.Time        // optional hint for when it will be available
}

// AttemptOutput carries a finished Attempt's exit code and captured output tails (bounded like
// detection input) for session extraction.
type AttemptOutput struct {
	ExitCode int
	Stdout   []byte
	Stderr   []byte
}

// AvailabilityState reports the result of a provider availability probe.
type AvailabilityState int

const (
	// Available means the provider is usable now.
	Available AvailabilityState = iota
	// Unavailable means the provider is known to be unusable right now.
	Unavailable
	// Unsupported means the provider offers no cheap availability check.
	Unsupported
)

// String returns the human-readable name of the AvailabilityState.
func (s AvailabilityState) String() string {
	switch s {
	case Available:
		return "available"
	case Unavailable:
		return "unavailable"
	case Unsupported:
		return "unsupported"
	default:
		return "unsupported"
	}
}
